spring:
  application:
    name: gatway-service
server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    preferIpAddress: false