spring:
  application:
    name: eureka-service
server:
  port: 8090

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/