spring:
  application:
    name: config-client
  profiles:
    active: development
  server:
    port: 8084


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    preferIpAddress: true


logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG